export const MainData = [
  { title: "مامور توضیع", name: "" },
  { title: "ثبت سفارش", name: "" },
  { title: "صدور فاکتور", name: "" },
  { title: "ویرایش محصول", name: "" },
  { title: " شارژ کالا", name: "" },
  { title: "ثبت کار بر خریدار", name: "" },
  { title: " ثبت کاربر سیستم", name: "" },
  { title: " مدیریت دسترسی", name: "" },
  { title: " ایجاد دسترسی ", name: "" },
  { title: " اطلاعات کاربران ", name: "" },
  { title: " ثبت فروشگاه ", name: "" },
  { title: " ثبت ارگان ", name: "" },
  { title: " انبار گرددانی ", name: "" },
  { title: " اطلاعات انبار ", name: "" },
  { title: " سابقه خرید ", name: "" },
  { title: " سفارش ها  ", name: "" },
  { title: " بایگانی شده ", name: "" },
  { title: " اطلاع رسانی ", name: "" },
  { title: " مدیریت برنامه ", name: "" },
  { title: " تبلغات ", name: "" },
  { title: " کدتخفیف ", name: "" },
  { title: " آمار و پایش داده  ", name: "" },
  { title: " مدیریت کارکنان ", name: "" },
  { title: " انبار فروشگاه ", name: "" },
];
